build: build-p1 build-p2 build-p3 build-p4 build-bonus

build-p1:
	gcc -g -std=gnu99 schimbare.c -o p1 -Wall -lm

build-p2:
	gcc -g -std=gnu99 reprezentanti.c -o p2 -Wall -lm

build-p3:
	gcc -g -std=gnu99 drumuri.c -o p3 -Wall -lm

build-p4:
	gcc -g -std=gnu99 labirint.c -o p4 -Wall -lm

build-bonus:
	gcc -g -std=gnu99 bonus.c -o bonus -Wall -lm

run-p1:
	./p1

run-p2:
	./p2

run-p3:
	./p3

run-p4:
	./p4

run-p5:
	./bonus

clean:
	rm -rf p1 p2 p3 p4 bonus
